In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [63]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import numpy as np

In [64]:
#target1,2,3 : autogluon, sample_napaurg, stacking3model
path = '/content/gdrive/My Drive/2025_dacon_etri/data/'

train_file_name2 = "submission_with_proba_0.6351_xgboost_best_0.625.csv"
submission_df2 = pd.read_csv(path+train_file_name2, encoding='utf8')

In [28]:
submission_df2.head(10)

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,Q1_class0_proba,Q1_class1_proba,Q2_class0_proba,Q2_class1_proba,Q3_class0_proba,Q3_class1_proba,S2_class0_proba,S2_class1_proba,S3_class0_proba,S3_class1_proba,S1_class0_proba,S1_class1_proba,S1_class2_proba
0,id01,2024-07-31,2024-07-30,0,1,0,1,1,1,0.699450,0.300550,0.150592,0.849408,0.596635,0.403365,0.190777,0.809223,0.003399,0.996601,0.231418,0.753383,0.015198
1,id01,2024-08-01,2024-07-31,0,1,0,0,1,1,0.961218,0.038782,0.442986,0.557014,0.819751,0.180249,0.216173,0.783827,0.009202,0.990798,0.591060,0.405469,0.003471
2,id01,2024-08-02,2024-08-01,0,0,1,0,0,1,0.509894,0.490106,0.559810,0.440190,0.188978,0.811022,0.547986,0.452014,0.167583,0.832417,0.812271,0.176203,0.011526
3,id01,2024-08-03,2024-08-02,1,0,0,1,1,1,0.335246,0.664754,0.641686,0.358314,0.695864,0.304136,0.173396,0.826604,0.094550,0.905450,0.213686,0.770492,0.015822
4,id01,2024-08-04,2024-08-03,1,1,1,1,1,1,0.192067,0.807933,0.089397,0.910603,0.061404,0.938596,0.199612,0.800388,0.013583,0.986417,0.021630,0.840266,0.138104
5,id01,2024-08-06,2024-08-05,0,0,0,0,1,1,0.708376,0.291624,0.758112,0.241888,0.758419,0.241581,0.281388,0.718612,0.322218,0.677782,0.807860,0.174171,0.017968
6,id01,2024-08-07,2024-08-06,1,0,0,0,0,1,0.495494,0.504506,0.911442,0.088558,0.580348,0.419652,0.743732,0.256268,0.156440,0.843560,0.918307,0.078225,0.003468
7,id01,2024-08-09,2024-08-08,1,0,0,0,1,1,0.474775,0.525225,0.728305,0.271695,0.631575,0.368425,0.212118,0.787882,0.393546,0.606454,0.775921,0.190745,0.033333
8,id01,2024-08-10,2024-08-09,1,0,0,1,1,1,0.280978,0.719022,0.845466,0.154534,0.816940,0.183060,0.269730,0.730270,0.106839,0.893161,0.451176,0.531044,0.017780
9,id01,2024-08-12,2024-08-11,0,1,1,1,1,1,0.827493,0.172507,0.072818,0.927182,0.012914,0.987086,0.060730,0.939270,0.009204,0.990796,0.050552,0.743890,0.205557

In [29]:
submission_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   subject_id       250 non-null    object
 1   sleep_date       250 non-null    object
 2   lifelog_date     250 non-null    object
 3   Q1               250 non-null    int64
 4   Q2               250 non-null    int64
 5   Q3               250 non-null    int64
 6   S1               250 non-null    int64
 7   S2               250 non-null    int64
 8   S3               250 non-null    int64
 9   Q1_class0_proba  250 non-null    float64
 10  Q1_class1_proba  250 non-null    float64
 11  Q2_class0_proba  250 non-null    float64
 12  Q2_class1_proba  250 non-null    float64
 13  Q3_class0_proba  250 non-null    float64
 14  Q3_class1_proba  250 non-null    float64
 15  S2_class0_proba  250 non-null    float64
 16  S2_class1_proba  250 non-null    float64
 17  S3_class0_proba  250 non-null    float64
 18  S3_class1_proba  250 non-null    float64
 19  S1_class0_proba  250 non-null    float64
 20  S1_class1_proba  250 non-null    float64
 21  S1_class2_proba  250 non-null    float64
dtypes: float64(13), int64(6), object(3)
memory usage: 43.1+ KB

In [65]:
#target1,2,3 : autogluon, sample_napaurg, stacking3model
path = '/content/gdrive/My Drive/2025_dacon_etri/data/'

train_file_name1 = "submission_with_proba_0.6359_lightgbm_best_0.628.csv"
submission_df = pd.read_csv(path+train_file_name1, encoding='utf8')

In [66]:
submission_df.head(10)

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,Q1_class0_proba,Q1_class1_proba,Q2_class0_proba,Q2_class1_proba,Q3_class0_proba,Q3_class1_proba,S2_class0_proba,S2_class1_proba,S3_class0_proba,S3_class1_proba,S1_class0_proba,S1_class1_proba,S1_class2_proba
0,id01,2024-07-31,2024-07-30,0,1,0,1,1,1,0.694731,0.305269,0.276447,0.723553,0.618559,0.381441,0.281124,0.718876,0.040890,0.959110,0.174016,0.785635,0.040349
1,id01,2024-08-01,2024-07-31,0,0,0,0,1,1,0.930532,0.069468,0.573832,0.426168,0.683876,0.316124,0.262697,0.737303,0.044606,0.955394,0.546225,0.431437,0.022337
2,id01,2024-08-02,2024-08-01,0,0,1,0,1,1,0.721248,0.278752,0.628254,0.371746,0.380031,0.619969,0.444964,0.555036,0.326699,0.673301,0.643307,0.324128,0.032565
3,id01,2024-08-03,2024-08-02,1,0,0,1,1,1,0.446527,0.553473,0.571672,0.428328,0.674796,0.325204,0.254776,0.745224,0.246633,0.753367,0.436449,0.485027,0.078523
4,id01,2024-08-04,2024-08-03,1,1,1,1,1,1,0.387579,0.612421,0.130888,0.869112,0.113978,0.886022,0.346771,0.653229,0.043514,0.956486,0.082702,0.629940,0.287359
5,id01,2024-08-06,2024-08-05,0,0,0,0,1,1,0.745126,0.254874,0.775991,0.224009,0.611917,0.388083,0.342127,0.657873,0.292025,0.707975,0.707826,0.255283,0.036891
6,id01,2024-08-07,2024-08-06,0,0,0,0,0,1,0.647988,0.352012,0.724095,0.275905,0.662671,0.337329,0.508867,0.491133,0.194803,0.805197,0.875594,0.105546,0.018859
7,id01,2024-08-09,2024-08-08,0,0,0,0,1,1,0.554252,0.445748,0.633665,0.366335,0.689331,0.310669,0.211347,0.788653,0.328605,0.671395,0.674033,0.251911,0.074057
8,id01,2024-08-10,2024-08-09,1,0,0,0,1,1,0.401939,0.598061,0.762296,0.237704,0.566904,0.433096,0.323149,0.676851,0.228046,0.771954,0.522691,0.422524,0.054785
9,id01,2024-08-12,2024-08-11,0,1,1,1,1,1,0.669602,0.330398,0.231514,0.768486,0.067943,0.932057,0.153331,0.846669,0.051990,0.948010,0.081404,0.660126,0.258470

In [67]:
submission_df["S1"].value_counts()

S1
1    147
0     76
2     27
Name: count, dtype: int64

In [68]:
submission_df["Q1_class0_proba_pv"] = 0.9*submission_df["Q1_class0_proba"] + 0.1*submission_df2["Q1_class0_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["Q1_class1_proba_pv"] = 0.9*submission_df["Q1_class1_proba"] + 0.1*submission_df2["Q1_class1_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["Q2_class0_proba_pv"] = 0.9*submission_df["Q2_class0_proba"] + 0.1*submission_df2["Q2_class0_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["Q2_class1_proba_pv"] = 0.9*submission_df["Q2_class1_proba"] + 0.1*submission_df2["Q2_class1_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["Q3_class0_proba_pv"] = 0.9*submission_df["Q3_class0_proba"] + 0.1*submission_df2["Q3_class0_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["Q3_class1_proba_pv"] = 0.9*submission_df["Q3_class1_proba"] + 0.1*submission_df2["Q3_class1_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["S1_class0_proba_pv"] = 0.9*submission_df["S1_class0_proba"] + 0.1*submission_df2["S1_class0_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["S1_class1_proba_pv"] = 0.9*submission_df["S1_class1_proba"] + 0.1*submission_df2["S1_class1_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["S1_class2_proba_pv"] = 0.9*submission_df["S1_class2_proba"] + 0.1*submission_df2["S1_class2_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["S2_class0_proba_pv"] = 0.9*submission_df["S2_class0_proba"] + 0.1*submission_df2["S2_class0_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["S2_class1_proba_pv"] = 0.9*submission_df["S2_class1_proba"] + 0.1*submission_df2["S2_class1_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["S3_class0_proba_pv"] = 0.9*submission_df["S3_class0_proba"] + 0.1*submission_df2["S3_class0_proba"] # 1등 과 2등 6:4 비율로 적용
submission_df["S3_class1_proba_pv"] = 0.9*submission_df["S3_class1_proba"] + 0.1*submission_df2["S3_class1_proba"] # 1등 과 2등 6:4 비율로 적용

In [69]:
# 모든 열을 다 보여주도록 설정
pd.set_option('display.max_columns', None)

In [70]:
submission_df.head(10)

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,Q1_class0_proba,Q1_class1_proba,Q2_class0_proba,Q2_class1_proba,Q3_class0_proba,Q3_class1_proba,S2_class0_proba,S2_class1_proba,S3_class0_proba,S3_class1_proba,S1_class0_proba,S1_class1_proba,S1_class2_proba,Q1_class0_proba_pv,Q1_class1_proba_pv,Q2_class0_proba_pv,Q2_class1_proba_pv,Q3_class0_proba_pv,Q3_class1_proba_pv,S1_class0_proba_pv,S1_class1_proba_pv,S1_class2_proba_pv,S2_class0_proba_pv,S2_class1_proba_pv,S3_class0_proba_pv,S3_class1_proba_pv
0,id01,2024-07-31,2024-07-30,0,1,0,1,1,1,0.694731,0.305269,0.276447,0.723553,0.618559,0.381441,0.281124,0.718876,0.040890,0.959110,0.174016,0.785635,0.040349,0.695203,0.304797,0.263861,0.736139,0.616367,0.383633,0.179756,0.782410,0.037834,0.272089,0.727911,0.037141,0.962859
1,id01,2024-08-01,2024-07-31,0,0,0,0,1,1,0.930532,0.069468,0.573832,0.426168,0.683876,0.316124,0.262697,0.737303,0.044606,0.955394,0.546225,0.431437,0.022337,0.933600,0.066400,0.560748,0.439252,0.697463,0.302537,0.550709,0.428841,0.020451,0.258045,0.741956,0.041066,0.958934
2,id01,2024-08-02,2024-08-01,0,0,1,0,1,1,0.721248,0.278752,0.628254,0.371746,0.380031,0.619969,0.444964,0.555036,0.326699,0.673301,0.643307,0.324128,0.032565,0.700112,0.299888,0.621410,0.378590,0.360926,0.639074,0.660203,0.309335,0.030462,0.455266,0.544734,0.310788,0.689212
3,id01,2024-08-03,2024-08-02,1,0,0,1,1,1,0.446527,0.553473,0.571672,0.428328,0.674796,0.325204,0.254776,0.745224,0.246633,0.753367,0.436449,0.485027,0.078523,0.435399,0.564601,0.578674,0.421326,0.676903,0.323097,0.414173,0.513574,0.072253,0.246638,0.753362,0.231425,0.768575
4,id01,2024-08-04,2024-08-03,1,1,1,1,1,1,0.387579,0.612421,0.130888,0.869112,0.113978,0.886022,0.346771,0.653229,0.043514,0.956486,0.082702,0.629940,0.287359,0.368028,0.631972,0.126739,0.873261,0.108721,0.891279,0.076595,0.650972,0.272433,0.332055,0.667945,0.040520,0.959480
5,id01,2024-08-06,2024-08-05,0,0,0,0,1,1,0.745126,0.254874,0.775991,0.224009,0.611917,0.388083,0.342127,0.657873,0.292025,0.707975,0.707826,0.255283,0.036891,0.741451,0.258549,0.774203,0.225797,0.626567,0.373433,0.717829,0.247172,0.034998,0.336053,0.663947,0.295044,0.704956
6,id01,2024-08-07,2024-08-06,0,0,0,0,0,1,0.647988,0.352012,0.724095,0.275905,0.662671,0.337329,0.508867,0.491133,0.194803,0.805197,0.875594,0.105546,0.018859,0.632738,0.367262,0.742830,0.257170,0.654439,0.345561,0.879866,0.102814,0.017320,0.532353,0.467647,0.190967,0.809033
7,id01,2024-08-09,2024-08-08,0,0,0,0,1,1,0.554252,0.445748,0.633665,0.366335,0.689331,0.310669,0.211347,0.788653,0.328605,0.671395,0.674033,0.251911,0.074057,0.546304,0.453696,0.643129,0.356871,0.683556,0.316444,0.684221,0.245794,0.069984,0.211424,0.788576,0.335099,0.664901
8,id01,2024-08-10,2024-08-09,1,0,0,0,1,1,0.401939,0.598061,0.762296,0.237704,0.566904,0.433096,0.323149,0.676851,0.228046,0.771954,0.522691,0.422524,0.054785,0.389843,0.610157,0.770613,0.229387,0.591908,0.408092,0.515540,0.433376,0.051084,0.317807,0.682193,0.215926,0.784074
9,id01,2024-08-12,2024-08-11,0,1,1,1,1,1,0.669602,0.330398,0.231514,0.768486,0.067943,0.932057,0.153331,0.846669,0.051990,0.948010,0.081404,0.660126,0.258470,0.685392,0.314608,0.215645,0.784355,0.062440,0.937560,0.078319,0.668502,0.253179,0.144071,0.855929,0.047711,0.952289

In [71]:
# Q1: 클래스 확률 비교 후 더 큰 쪽 클래스 선택
submission_df['Q1_pred'] = submission_df[['Q1_class0_proba_pv', 'Q1_class1_proba_pv']].idxmax(axis=1)

# 컬럼명에서 'classX_proba_pv' 중 'X'만 추출해서 정수형 클래스값으로 변환
submission_df['Q1_pred'] = submission_df['Q1_pred'].str.extract(r'class(\d+)_proba_pv').astype(int)

In [72]:
# Q1: 클래스 확률 비교 후 더 큰 쪽 클래스 선택
submission_df['Q2_pred'] = submission_df[['Q2_class0_proba_pv', 'Q2_class1_proba_pv']].idxmax(axis=1)

# 컬럼명에서 'classX_proba_pv' 중 'X'만 추출해서 정수형 클래스값으로 변환
submission_df['Q2_pred'] = submission_df['Q2_pred'].str.extract(r'class(\d+)_proba_pv').astype(int)

In [73]:
# Q1: 클래스 확률 비교 후 더 큰 쪽 클래스 선택
submission_df['Q3_pred'] = submission_df[['Q3_class0_proba_pv', 'Q3_class1_proba_pv']].idxmax(axis=1)

# 컬럼명에서 'classX_proba_pv' 중 'X'만 추출해서 정수형 클래스값으로 변환
submission_df['Q3_pred'] = submission_df['Q3_pred'].str.extract(r'class(\d+)_proba_pv').astype(int)

In [74]:
# S1: 클래스 확률 비교 후 더 큰 쪽 클래스 선택
submission_df['S1_pred'] = submission_df[['S1_class0_proba_pv', 'S1_class1_proba_pv', 'S1_class2_proba_pv']].idxmax(axis=1)

# 컬럼명에서 'classX_proba_pv' 중 'X'만 추출해서 정수형 클래스값으로 변환
submission_df['S1_pred'] = submission_df['S1_pred'].str.extract(r'class(\d+)_proba_pv').astype(int)

In [75]:
# Q1: 클래스 확률 비교 후 더 큰 쪽 클래스 선택
submission_df['S2_pred'] = submission_df[['S2_class0_proba_pv', 'S2_class1_proba_pv']].idxmax(axis=1)

# 컬럼명에서 'classX_proba_pv' 중 'X'만 추출해서 정수형 클래스값으로 변환
submission_df['S2_pred'] = submission_df['S2_pred'].str.extract(r'class(\d+)_proba_pv').astype(int)

In [76]:
# Q1: 클래스 확률 비교 후 더 큰 쪽 클래스 선택
submission_df['S3_pred'] = submission_df[['S3_class0_proba_pv', 'S3_class1_proba_pv']].idxmax(axis=1)

# 컬럼명에서 'classX_proba_pv' 중 'X'만 추출해서 정수형 클래스값으로 변환
submission_df['S3_pred'] = submission_df['S3_pred'].str.extract(r'class(\d+)_proba_pv').astype(int)

In [77]:
submission_df.head()

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,Q1_class0_proba,Q1_class1_proba,Q2_class0_proba,Q2_class1_proba,Q3_class0_proba,Q3_class1_proba,S2_class0_proba,S2_class1_proba,S3_class0_proba,S3_class1_proba,S1_class0_proba,S1_class1_proba,S1_class2_proba,Q1_class0_proba_pv,Q1_class1_proba_pv,Q2_class0_proba_pv,Q2_class1_proba_pv,Q3_class0_proba_pv,Q3_class1_proba_pv,S1_class0_proba_pv,S1_class1_proba_pv,S1_class2_proba_pv,S2_class0_proba_pv,S2_class1_proba_pv,S3_class0_proba_pv,S3_class1_proba_pv,Q1_pred,Q2_pred,Q3_pred,S1_pred,S2_pred,S3_pred
0,id01,2024-07-31,2024-07-30,0,1,0,1,1,1,0.694731,0.305269,0.276447,0.723553,0.618559,0.381441,0.281124,0.718876,0.040890,0.959110,0.174016,0.785635,0.040349,0.695203,0.304797,0.263861,0.736139,0.616367,0.383633,0.179756,0.782410,0.037834,0.272089,0.727911,0.037141,0.962859,0,1,0,1,1,1
1,id01,2024-08-01,2024-07-31,0,0,0,0,1,1,0.930532,0.069468,0.573832,0.426168,0.683876,0.316124,0.262697,0.737303,0.044606,0.955394,0.546225,0.431437,0.022337,0.933600,0.066400,0.560748,0.439252,0.697463,0.302537,0.550709,0.428841,0.020451,0.258045,0.741956,0.041066,0.958934,0,0,0,0,1,1
2,id01,2024-08-02,2024-08-01,0,0,1,0,1,1,0.721248,0.278752,0.628254,0.371746,0.380031,0.619969,0.444964,0.555036,0.326699,0.673301,0.643307,0.324128,0.032565,0.700112,0.299888,0.621410,0.378590,0.360926,0.639074,0.660203,0.309335,0.030462,0.455266,0.544734,0.310788,0.689212,0,0,1,0,1,1
3,id01,2024-08-03,2024-08-02,1,0,0,1,1,1,0.446527,0.553473,0.571672,0.428328,0.674796,0.325204,0.254776,0.745224,0.246633,0.753367,0.436449,0.485027,0.078523,0.435399,0.564601,0.578674,0.421326,0.676903,0.323097,0.414173,0.513574,0.072253,0.246638,0.753362,0.231425,0.768575,1,0,0,1,1,1
4,id01,2024-08-04,2024-08-03,1,1,1,1,1,1,0.387579,0.612421,0.130888,0.869112,0.113978,0.886022,0.346771,0.653229,0.043514,0.956486,0.082702,0.629940,0.287359,0.368028,0.631972,0.126739,0.873261,0.108721,0.891279,0.076595,0.650972,0.272433,0.332055,0.667945,0.040520,0.959480,1,1,1,1,1,1

In [86]:
#target1,2,3 : autogluon, sample_napaurg, stacking3model
path = '/content/gdrive/My Drive/2025_dacon_etri/data/'

submission_file_name_0 = "submission_2_model_9_1_soft_voting_ensemble_verification.csv"
submission_df.to_csv(path+submission_file_name_0, index=False)
print(f"Saved 'finished")

Saved 'finished

In [78]:
submission_df["S1_pred"].value_counts()

S1_pred
1    144
0     77
2     29
Name: count, dtype: int64

In [79]:
submission_df2['Q1'] = submission_df['Q1_pred']
submission_df2['Q2'] = submission_df['Q2_pred']
submission_df2['Q3'] = submission_df['Q3_pred']
submission_df2['S1'] = submission_df['S1_pred']
submission_df2['S2'] = submission_df['S2_pred']
submission_df2['S3'] = submission_df['S3_pred']

In [80]:
submission_df2["S1"].value_counts()

S1
1    144
0     77
2     29
Name: count, dtype: int64

In [81]:
#target1,2,3 : autogluon, sample_napaurg, stacking3model
path = '/content/gdrive/My Drive/2025_dacon_etri/data/'

train_file_name3 = "submission_3_hard_voting.csv"
submission_df3 = pd.read_csv(path+train_file_name3, encoding='utf8')

In [82]:
submission_df3.head()

  subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3
0       id01  2024-07-31   2024-07-30   0   1   0   1   1   1
1       id01  2024-08-01   2024-07-31   0   0   0   0   1   1
2       id01  2024-08-02   2024-08-01   0   0   1   0   1   1
3       id01  2024-08-03   2024-08-02   1   0   0   1   1   1
4       id01  2024-08-04   2024-08-03   1   1   1   1   1   1

In [83]:
submission_df3['Q1'] = submission_df['Q1_pred']
submission_df3['Q2'] = submission_df['Q2_pred']
submission_df3['Q3'] = submission_df['Q3_pred']
submission_df3['S1'] = submission_df['S1_pred']
submission_df3['S2'] = submission_df['S2_pred']
submission_df3['S3'] = submission_df['S3_pred']

In [84]:
submission_file_name = "submission_2_model_9_1_soft_voting_ensemble.csv"
submission_df3.to_csv(path+submission_file_name, index=False)
print(f"Saved 'finished")

Saved 'finished

In [85]:
submission_df3["S1"].value_counts()

S1
1    144
0     77
2     29
Name: count, dtype: int64

In [61]:
submission_df3.head()

  subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3
0       id01  2024-07-31   2024-07-30   0   1   0   1   1   1
1       id01  2024-08-01   2024-07-31   0   0   0   0   1   1
2       id01  2024-08-02   2024-08-01   0   0   1   0   1   1
3       id01  2024-08-03   2024-08-02   1   0   0   1   1   1
4       id01  2024-08-04   2024-08-03   1   1   1   1   1   1